# Generated by Django 2.0.3 on 2018-04-27 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traveller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_no', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_url', models.TextField()),
                ('status', models.TextField(max_length=20)),
                ('fee', models.FloatField()),
                ('creation_time', models.DateTimeField(verbose_name='Order Creation Time')),
                ('delivery_date', models.DateField(null=True, verbose_name='Delivery Date')),
                ('receive_date', models.DateField(null=True, verbose_name='Receive Date')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connector',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='connector',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Order'),
        ),
        migrations.AddField(
            model_name='connector',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveller.Traveller'),
        ),
    ]
