# Generated by Django 2.0.3 on 2018-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='aadhar_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='traveller',
            name='aadhar_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
